<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../asset/public.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
</head>

<style>
    .add_form {
        background-color: white;
        padding: 1em;
        border-radius: 20px;
        margin: auto;
        margin-top: 1em;
        max-width: 1120px;

    }

    .error {
        color: red;
        font-weight: bold;
    }
</style>

<body>
    <div class="active">
        <div class="hd">
            <div class="icon">
                <a href="movie_web.php"><img class="icon" src="https://w7.pngwing.com/pngs/130/1021/png-transparent-movie-logo-movie-logo-film-tape-cinema.png" alt=""></a>
            </div>

            <div>
                <div class="user">
                    <?php
                    if (isset($_SESSION["name"])) {
                        echo '<span class= "name">' . $_SESSION["name"] . '</span>';
                        echo '<a href="..index.php"><span class ="log">Log out</span></a>';
                    } else {
                        echo '<a href="index.php"><span class = "log">Log in</span></a>';
                    } ?>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="home_page">
            <div class="genres">
                <a href="index.php">Trang chủ</a>
            </div>
            <?php
            foreach ($genres as $genre) {
                echo ('<div class="genres">');
                echo ('<a href="list_movie.php?id=' . $genre->getGenreID() . '">' . $genre->getName() . '</a>');
                echo ("</div>\n");
            }

            ?>
            <div class="clear"></div>
        </div>
    </div>
    <div class="add_form">
        <h1>Add A New Film</h1>
        <form method="post">
            <p>Title:
                <input type="text" name="title" size="40" value="<?php if (isset($_POST["title"])) {
                                                                        echo $_POST["title"];
                                                                    } else {
                                                                        echo "";
                                                                    } ?>">
            </p>
            <p>Genre:
                <?php
                foreach ($genres as $genre) {
                    $checked = "";
                    if (isset($_POST["genres"])) {
                        foreach ($_POST["genres"] as $gen) {
                            if ($genre->getGenreID() == $gen) {
                                $checked = "checked";
                                break;
                            }
                        }
                    }
                    echo '<label for="' . $genre->getGenreID() . '">' . $genre->getName() . '</label>';
                    echo '<input type="checkbox" name="genres[]" id="' . $genre->getGenreID() . '" value="' . $genre->getGenreID() . '"' . $checked . '>';
                }
                ?>

            </p>
            <p>Manufacture of year:<input type="year" name="manufacture"></p>
            <p>Director:
                <label for="director"></label>
                <select name="director" id="director">
                    <?php
                    foreach ($directors as $director) {
                        $selected = "";
                        if (isset($_POST["director"])) {
                            if ($_POST["director"] == $director->getPersonID()) {
                                $selected = " selected ";
                            }
                        }

                        echo '<option value ="' . $director->getPersonID() . '"' . $selected . '>' . $director->getName() . '</option>';
                    }
                    ?>
                </select>
            </p>
            <p>Actors:
                <?php
                foreach ($actors as $actor) {
                    $checked = "";
                    if (isset($_POST["actors"])) {
                        foreach ($_POST["actors"] as $act) {
                            if ($actor->getPersonID() == $act) {
                                $checked = "checked";
                                break;
                            }
                        }
                    }
                    echo '<label for="' . $actor->getPersonID() . '">' . $actor->getName() . '</label>';
                    echo '<input type="checkbox" name="actors[]" id="' . $actor->getPersonID() . '" value="' . $actor->getPersonID() . '"' . $checked . '>';
                }
                ?>

            </p>
            <p>Img link: <input type="url" name="img" value="<?php if (isset($_POST["img"])) {
                                                                    echo $_POST["img"];
                                                                } else {
                                                                    echo "";
                                                                } ?>"></p>
            <p>Link: <input type="url" name="link" value="<?php if (isset($_POST["link"])) {
                                                                echo $_POST["link"];
                                                            } else {
                                                                echo "";
                                                            } ?>"></p>
            <p>Description: <input type="text" name="description" value="<?php if (isset($_POST["description"])) {
                                                                                echo $_POST["description"];
                                                                            } else {
                                                                                echo "";
                                                                            } ?>"></p>
            <p><input type="submit" name="addNew" value="Add New" /></p>
        </form>
        <div class="error">
            <?php echo $error ?>
        </div>
    </div>
</body>