<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href='../asset/admin.css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
</head>

<body>
    <div class="active">
        <div class="hd">
            <div class="icon">
                <a href="index.php"><img class="icon" src="https://w7.pngwing.com/pngs/130/1021/png-transparent-movie-logo-movie-logo-film-tape-cinema.png" alt=""></a>
  </div>

            <div>
                <div class="user">
                    <?php
                    if (isset($_SESSION["name"])) {
                        echo '<span class= "user_name">' . $_SESSION["name"] . '</span>';
                        echo '<a href="../index.php"><span class ="log">Log out</span></a>';
                    } else {
                        echo '<a href="../log.php"><span class = "log">Log in</span></a>';
                    } ?>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="home_page">
            <div class="genres">
                <a href="index.php">Trang chủ</a>
            </div>
          
            <?php
            foreach ($genres as $genre) {
                echo ('<div class="genres">');
                echo ('<a href="list_movie.php?id='.$genre->getGenreID() .'">'. $genre->getName() . '</a>');
                echo ("</div>\n");
            }

            ?>
            <form method="post">
                <button class="add" type="submit" name="add">Add film</button>
            </form>
            <div class="clear"></div>
        </div>
        <div> 
            <?php if (isset($_SESSION["update"])) { echo $_SESSION["update"]; unset($_SESSION["update"]);}
                if (isset($_SESSION["delete"])) { echo $_SESSION["delete"]; unset ($_SESSION["delete"]);}
            ?>
        </div>
        <div class="films">
            <?php
            foreach ($films as $film) {
                echo '<div class="movie"><a href="view.php"><img  src="' . $film->getImg() . '">';
                echo '<div class="name">' . $film->getTitle() . ' (' . $film->getManufacture() . ') </div><div class="clear"></div></a>' . "\n";
                echo ('<form method="post"><input type="hidden" ');
                echo ('name="filmID" value="' . $film->getFilmID() . '">' . "\n");
                echo ('<button class="button" type="submit" name="update" >Update</button>');
                echo ('<button class="button" type="submit" name="delete" >Delete</button>');
                echo ("\n</form>\n");
                echo '<div class="clear"></div></div>';
            }
            ?>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>
    <div class="clear"></div>
</body>

</html>