<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="asset\login.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
</head>

<body>
    <div class="active">
        <div class="hd">
            <div class="icon">
                <a href="movie_web.php"><img class="icon" src="https://w7.pngwing.com/pngs/130/1021/png-transparent-movie-logo-movie-logo-film-tape-cinema.png" alt=""></a>
            </div>

            <div class="clear"></div>
        </div>
        <div class="home_page">
            <div class="genre">
                <a href="index.php">Trang chủ</a>
            </div>
            <?php
            foreach ($genres as $genre) {
                echo ('<div class="genre">');
                echo ('<a href="list_movie.php?id=' . $genre->getGenreID() . '">' . $genre->getName() . '</a>');
                echo ("</div>\n");
            }

            ?>
            <div class="clear"></div>
        </div>
    </div>
</body>


<div class="formm">
    <form method="post">
        <div>
            <div class="form">
                <input class="distan" type="text" name="username" placeholder="Username" aria-label="Username">
            </div>
            <div class="form">
                <input class="distan" type="password" name="password" placeholder="Password" aria-label="password">
            </div>
        </div>
        <div class="form">
            <button class="distan submit" type="submit" name="submit"> <b>LOG IN</b></button>
        </div>
        <div>
            <?php
            if (isset($error)) {
                echo ('<p style="color:red">' . $error . "</p>\n");
                unset($error);
            }
            ?>
        </div>
        <a href="sign_in.php" class ="sign">Create a new account</a>
        <div class="clear"></div>

    </form>
</div>



</html>