<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../asset/public.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
</head>

<style>
    .update_form {
        background-color: white;
        padding: 1em;
        border-radius: 20px;
        margin: auto;
        margin-top: 1em;
        max-width: 1120px;
        
    }

</style>

<body>
    <div class="active">
        <div class="hd">
            <div class="icon">
                <a href="movie_web.php"><img class="icon" src="https://w7.pngwing.com/pngs/130/1021/png-transparent-movie-logo-movie-logo-film-tape-cinema.png" alt=""></a>
            </div>

            <div>
                <div class="user">
                    <?php
                    if (isset($_SESSION["name"])) {
                        echo '<span class= "name">' . $_SESSION["name"] . '</span>';
                        echo '<a href="..index.php"><span class ="log">Log out</span></a>';
                    } else {
                        echo '<a href="index.php"><span class = "log">Log in</span></a>';
                    } ?>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="home_page">
            <div class="genres">
                <a href="index.php">Trang chủ</a>
            </div>

            <?php
            foreach ($genres as $genre) {
                echo ('<div class="genres">');
                echo ('<a href="list_movie.php?id='.$genre->getGenreID() .'">'. $genre->getName() . '</a>');
                echo ("</div>\n");
            }

            ?>
            <div class="clear"></div>
        </div>
    </div>
    <div class="update_form">
    <h1>Update Film</h1>
    <form method="post">
        <p>Title: 
            <label for="film"></label>
            <select name="filmID" id="film" onchange="this.form.submit()">
            <?php
                foreach ($films as $val) {
                 $selected = ($val->getFilmID() == $film->getFilmID()) ? "selected" :"";
                 echo '<option value ="' . $val->getFilmID().'" '.$selected.' >'. $val->getTitle() . '</option>';
                 unset ($selected);
                }
                ?>
            </select>
        </p>

        <p>Genre:
            <?php
            foreach ($genres as $gen) {
                foreach ($film->getGenres() as $genre)
                {
                    if ($gen->getGenreID() == $genre->getGenreID()) {
                        $checked = "checked";
                        break;
                    } else {
                        $checked = "";
                    }

                }
                echo '<label for="' . $gen->getName() . '">' . $gen->getName(). '</label>';
                echo '<input type="checkbox" name="genres[]" id="' .$gen->getName() . '" value="' .$gen->getGenreID() . '" ' . $checked . '>';
                unset($checked);
            }
            ?>
        </p>

        <p>Manufacture of year:<input type="year" name="manufacture" value="<?php echo $film->getManufacture()?>"></p>

        <p>Director:
            <label for="director"></label>
            <select name="director" id="director">
                <?php
                foreach ($directors as $director)
                {
                    $selected = ($director->getPersonID() == $film->getDirector()->getPersonID()) ? "selected" : "";
                    echo '<option value ="' . $director->getPersonID().'" ' . $selected .'>' . $director->getName(). '</option>';
                }
                ?>
            </select>
        </p>

        <p>Actors:
        <?php
           foreach ($actors as $val)
           {
               foreach ($film->getActors() as $actor)
               {
                   if ($val->getPersonID() == $actor->getPersonID()){
                       $checked = "checked";
                       break;
                   } else {
                       $checked = "";
                   }
               }
                echo '<label for="' . $val->getPersonID() . '">' . $val->getName() . '</label>';
                echo '<input type="checkbox" name="actors[]" id="' . $val->getPersonID(). '" value="' .$val->getPersonID(). '" ' . $checked . '>';
            }
            ?>

        </p>
        <p>Img link: <input type="url" name="img" value="<?php echo $film->getImg() ?>"></p>
        <p>Link: <input type="url" name="link" value="<?php echo $film->getLink() ?>"></p>
        <p><label for="des">Description:</label></p>
        <textarea name="description" id="des" ><?php echo $film->getDescription() ?></textarea>
        <p><input type="submit" name="update" value="Update" /></p>
    </form>
    </div>
</body>