<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../asset/public.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
</head>

<style>
    .update_form {
        background-color: white;
        padding: 1em;
        border-radius: 20px;
        margin: auto;
        margin-top: 1em;
        max-width: 1120px;
        
    }

</style>

<body>
    <div class="active">
        <div class="hd">
            <div class="icon">
                <a href="movie_web.php"><img class="icon" src="https://w7.pngwing.com/pngs/130/1021/png-transparent-movie-logo-movie-logo-film-tape-cinema.png" alt=""></a>
            </div>

            <div>
                <div class="user">
                    <?php
                    if (isset($_SESSION["name"])) {
                        echo '<span class= "name">' . $_SESSION["name"] . '</span>';
                        echo '<a href="..index.php"><span class ="log">Log out</span></a>';
                    } else {
                        echo '<a href="index.php"><span class = "log">Log in</span></a>';
                    } ?>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="home_page">
            <div class="genres">
                <a href="index.php">Trang chủ</a>
            </div>

           
            <?php
            while ($row1 = $genre1->fetch(PDO::FETCH_ASSOC)) {
                echo ('<div class="genres">');
                echo ('<form method="post"><input type="hidden" ');
                echo ('name="genre" value="' . $row1['name'] . '">' . "\n");
                echo ('<button class="genre_button" type="submit" >'.$row1['name'] .'</button>');
                echo ("\n</form></div>\n");
            }

            ?>
            <div class="clear"></div>
        </div>
    </div>
    <div class="update_form">
    <h1>Update Film</h1>
    <form method="post">
        <p>Title: 
            <label for="film"></label>
            <select name="filmID" id="film" onchange="this.form.submit()">
            <?php
                while ($row= $data_film->fetch(PDO::FETCH_ASSOC)) {
                 $selected = ($row["filmID"] == $filmID) ? "selected" :"";
                 echo '<option value ="' . $row["filmID"].'" '.$selected.' >'. $row["title"] . '</option>';
                 unset ($selected);
                }
                ?>
            </select>
        </p>

        <p>Genre:
            <?php
            while ($row2 = $genre2->fetch(PDO::FETCH_ASSOC)) {
                $checked = strpos($film["genres"],$row2["name"]) !== false ? "checked" : "";
                echo '<label for="' . $row2["name"] . '">' . $row2["name"] . '</label>';
                echo '<input type="checkbox" name="genres[]" id="' . $row2["name"] . '" value="' . $row2["genreID"] . '" ' . $checked . '>';
                unset($checked);
            }
            ?>
        </p>

        <p>Manufacture of year:<input type="year" name="manufacture" value="<?php echo $film['manufacture'] ?>"></p>
        <p>Director:
            <label for="director"></label>
            <select name="director" id="director">
                <?php
                while ($row3 = $director->fetch(PDO::FETCH_ASSOC)){
                $selected = ($film["director"] == $row3["name"]) ?"selected":"";
                echo '<option value ="' . $row3["personID"].'" ' . $selected .'>' . $row3["name"] . '</option>';
                }
                ?>
            </select>
        </p>

        <p>Actors:
        <?php
            while ($row4 = $actor->fetch(PDO::FETCH_ASSOC)) {
                $checked = strpos($film["actors"], $row4["name"]) !== false ? 'checked' : '';
                echo '<label for="' . $row4["name"] . '">' . $row4["name"] . '</label>';
                echo '<input type="checkbox" name="actors[]" id="' . $row4["name"] . '" value="' . $row4["personID"] . '" ' . $checked . '>';
            }
            ?>

        </p>
        <p>Img link: <input type="url" name="img" value="<?php echo $film['img'] ?>"></p>
        <p>Link: <input type="url" name="link" value="<?php echo $film['link'] ?>"></p>
        <p><label for="des">Description:</label></p>
        <textarea name="description" id="des" ><?php echo $film['description'] ?></textarea>
        <p><input type="submit" name="update" value="Update" /></p>
    </form>
    </div>
</body>