<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>phim</title>
    <link rel="stylesheet" type="text/css" href="asset\public.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
</head>

<body>
    <div class="active">
        <div class="hd">
            <div class="icon">
                <a href="index.php"><img class="icon" src="https://w7.pngwing.com/pngs/130/1021/png-transparent-movie-logo-movie-logo-film-tape-cinema.png" alt=""></a>
            </div>

            <div>
                <div class="user">
                    <?php
                    if (isset($_SESSION["name"])) {
                        echo '<span class= "name">' . $_SESSION["name"] . '</span>';
                        echo '<a href="admin\index.php"><span class ="log">Log out</span></a>';
                    } else {
                        echo '<a href="index.php?controller=admin.login&action=login"><span class = "log">Log in</span></a>';
                    } ?>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="home_page">
            <div class="genres">
                <a href="index.php">Trang chủ</a>
            </div>

            <?php
            foreach ($genres as $genre) {
                echo ('<div class="genres">');
                echo ('<a href="index.php?controller=front.film&action=listByCategory&id='.$genre->getGenreID() .'">'. $genre->getName() . '</a>');
                echo ("</div>\n");
            }

            ?>
            <a href=""></a>
            <div class="clear"></div>
        </div>
        <div class="films">
            <?php
            foreach ($films as $film) {
                echo '<div class="movie"><a href="index.php?controller=front.film&action=view&id='.$film->getFilmID().'"><img  src="' . $film->getImg() . '">';
                echo '<div class="name">' . $film->getTitle() . ' (' . $film->getManufacture() . ') </div><div class="clear"></div></a><div class="clear"></div></div>'."\n";
            }
            ?>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>
    <div class="clear"></div>
</body>

</html>