<div>
    <h1>Sign up</h1>
    <form method="post">
        <div>
            <p>Your name</p>
            <input type="text" name = "name">
            <p>Your Username</p>
            <input type="text" name="userName">
            <p>Password</p>
            <input type="password" name="password">
            <p>Confirm Password</p>
            <input type="password" name="confirmPassword">
            <input type="submit" name="submit" value="Sign up">
        </div>
    </form>
</div>