<form method="post">
    <p>Add a new person</p>
    <p>Name:<input type="text" name="name"></p>
    <p>Gender:
        <select name="gender" id="gender">
            <option value="male">Male</option>
            <option value="female">Female</option>
        </select>
    </p>
    <p>Birthday: <input type="year" name="birthday"></p>
    <p>Role:
        <select name="role">
            <option value="actor">Actor</option>
            <option value="director">Director</option>
        </select>
    </p>
    <input type="submit" name=Psubmit>
</form>